AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Bio-Optimization Data Lakehouse - Silver Layer
  S3 bucket, Glue database, ETL jobs, and crawler

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
  ProjectPrefix:
    Type: String
    Default: bio-lakehouse

Resources:
  # -------------------------------------------------------
  # S3 Bucket - Silver Layer
  # -------------------------------------------------------
  SilverBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectPrefix}-silver-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectPrefix
        - Key: Layer
          Value: silver

  # -------------------------------------------------------
  # Glue Database
  # -------------------------------------------------------
  SilverDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Name: bio_silver
        Description: Silver layer - cleaned and normalized bio-optimization data

  # -------------------------------------------------------
  # IAM Role for Glue Jobs
  # -------------------------------------------------------
  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectPrefix}-glue-job-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole'
      Policies:
        - PolicyName: GlueS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ReadBronze
                Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub
                    - 'arn:aws:s3:::${BronzeBucket}'
                    - BronzeBucket: !ImportValue
                        Fn::Sub: '${ProjectPrefix}-bronze-bucket'
                  - !Sub
                    - 'arn:aws:s3:::${BronzeBucket}/*'
                    - BronzeBucket: !ImportValue
                        Fn::Sub: '${ProjectPrefix}-bronze-bucket'
              - Sid: WriteSilver
                Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource:
                  - !GetAtt SilverBucket.Arn
                  - !Sub '${SilverBucket.Arn}/*'

  # -------------------------------------------------------
  # Glue ETL Jobs
  # -------------------------------------------------------
  OuraNormalizerJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${ProjectPrefix}-oura-normalizer'
      Role: !GetAtt GlueJobRole.Arn
      GlueVersion: '4.0'
      WorkerType: G.1X
      NumberOfWorkers: 2
      Timeout: 30
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${SilverBucket}/scripts/oura_normalizer.py'
        PythonVersion: '3'
      DefaultArguments:
        '--bronze_bucket': !ImportValue
          Fn::Sub: '${ProjectPrefix}-bronze-bucket'
        '--silver_bucket': !Ref SilverBucket
        '--extra-py-files': !Sub 's3://${SilverBucket}/scripts/bio_etl_utils.py'
        '--enable-metrics': 'true'
        '--enable-continuous-cloudwatch-log': 'true'
        '--job-language': python
      Tags:
        Project: !Ref ProjectPrefix

  PelotonNormalizerJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${ProjectPrefix}-peloton-normalizer'
      Role: !GetAtt GlueJobRole.Arn
      GlueVersion: '4.0'
      WorkerType: G.1X
      NumberOfWorkers: 2
      Timeout: 30
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${SilverBucket}/scripts/peloton_normalizer.py'
        PythonVersion: '3'
      DefaultArguments:
        '--bronze_bucket': !ImportValue
          Fn::Sub: '${ProjectPrefix}-bronze-bucket'
        '--silver_bucket': !Ref SilverBucket
        '--extra-py-files': !Sub 's3://${SilverBucket}/scripts/bio_etl_utils.py'
        '--enable-metrics': 'true'
        '--enable-continuous-cloudwatch-log': 'true'
        '--job-language': python
      Tags:
        Project: !Ref ProjectPrefix

  # -------------------------------------------------------
  # Glue Crawler - Auto-discover Silver schema
  # -------------------------------------------------------
  SilverCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub '${ProjectPrefix}-silver-crawler'
      Role: !GetAtt GlueJobRole.Arn
      DatabaseName: !Ref SilverDatabase
      Targets:
        S3Targets:
          - Path: !Sub 's3://${SilverBucket}/oura_daily_readiness/'
          - Path: !Sub 's3://${SilverBucket}/oura_daily_sleep/'
          - Path: !Sub 's3://${SilverBucket}/oura_daily_activity/'
          - Path: !Sub 's3://${SilverBucket}/peloton_workouts/'
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Tags:
        Project: !Ref ProjectPrefix

Outputs:
  SilverBucketName:
    Description: Silver layer S3 bucket
    Value: !Ref SilverBucket
    Export:
      Name: !Sub '${ProjectPrefix}-silver-bucket'

  SilverBucketArn:
    Description: Silver bucket ARN
    Value: !GetAtt SilverBucket.Arn
    Export:
      Name: !Sub '${ProjectPrefix}-silver-bucket-arn'

  SilverDatabaseName:
    Description: Glue database for Silver layer
    Value: !Ref SilverDatabase
    Export:
      Name: !Sub '${ProjectPrefix}-silver-database'

  GlueJobRoleArn:
    Description: Glue job IAM role ARN
    Value: !GetAtt GlueJobRole.Arn
    Export:
      Name: !Sub '${ProjectPrefix}-glue-role-arn'
